name: "\U0001F680 Ideas"
description: "Suggest a research idea \U0001F63B!"
title: 'idea: [DESCRIPTION]'
body:
  - type: textarea
    validations:
      required: true
    attributes:
      label: "Problem Statement"
      description: "Describe the problem you're facing"
      placeholder: |
        I'm always frustrated when ...

  - type: textarea
    validations:
      required: true
    attributes:
      label: "Idea"
      description: "Examples are welcome!"