services:
  asr:
    build:
      dockerfile: Dockerfile
    # network_mode: host
    ports:
      - "8000:8000"
    command: ["fastapi", "run", "asr.py", "--port", "8000"]
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [ gpu ]
